Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,7 +8,7 @@ on:
   # allows running the job manually at any time
   workflow_dispatch:
 
-  # run on every push on the master branch
+  # run on every push on the main branch
   push:
     branches:
     - main
@@ -22,6 +22,17 @@ jobs:
       GITHUB_USER: ULTRAPAIN
 
     steps:
+      # Set up Git configuration
+      - name: Configure Git
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub Actions"
+      # Handle Git error (exit code 128)
+      - name: Handle Git Error
+        continue-on-error: true
+        run: |
+          git pull origin main || true
+
       # generates a snake game from a GitHub user (<github_user_name>) contributions graph, output an SVG animation at <svg_out_path>
       - name: Generate github-contribution-grid-snake.svg
         uses: Platane/snk/svg-only@v2
@@ -30,12 +41,18 @@ jobs:
           outputs: |
             dist/github-contribution-grid-snake.svg
             dist/github-contribution-grid-snake-dark.svg?palette=github-dark
+
       # push the content of <build_dir> to a branch
       # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as a GitHub page
       - name: Push github-contribution-grid-snake.svg to the output branch
-        uses: crazy-max/ghaction-github-pages@v2.6.0
+        uses: crazy-max/ghaction-github-pages@latest
         with:
           target_branch: output
           build_dir: dist
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # Handle the deprecation of Node.js 12
+      - name: Update Node.js Version
+        uses: actions/setup-node@v2
+        with:
+          node-version: 16
